language: go
env:
  - TEST_ROOT=$HOME/test
go:
  - 1.4
before_install:
  - mkdir $TEST_ROOT
  - go get -u gopkg.in/logex.v1
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/chzyer/adrs
  - mkdir -p ../../chzyer/
  - cp -r ../muxque ../../chzyer/muxque
script:
  - ./goverall.sh
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=ccc.out
